name: goldenrod

description: >
  Golden-file expectations and test extensions for Dart and Flutter.
version: 0.1.0

homepage: https://github.com/matanlurey/goldenrod.dart

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  matcher: ^0.12.8
  meta: ^1.1.8

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.15.0
  test_coverage: ^0.4.1
